# Generated by Django 3.1.1 on 2020-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techniques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('difficulty', models.CharField(default='Easy', max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('tutorial', models.CharField(max_length=100)),
            ],
        ),
    ]
