# Generated by Django 3.1.1 on 2020-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0002_techniques'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniques',
            name='discipline',
            field=models.CharField(default='boxing', max_length=100),
        ),
    ]
