# Generated by Django 3.1.1 on 2020-10-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0003_techniques_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniques',
            name='mistakes',
            field=models.CharField(default='avoid', max_length=100),
        ),
    ]
