# Generated by Django 3.1.1 on 2020-10-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0004_techniques_mistakes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
