# Generated by Django 3.1.1 on 2020-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0005_auto_20201005_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniques',
            name='difficulty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='techniques',
            name='discipline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='techniques',
            name='mistakes',
            field=models.CharField(max_length=100),
        ),
    ]
