# Generated by Django 3.1.1 on 2020-10-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0006_auto_20201008_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Techniques',
            new_name='Technique',
        ),
    ]
