# Generated by Django 3.1.1 on 2020-10-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0007_auto_20201009_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_fights', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('promotions', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('highlight', models.CharField(max_length=25)),
            ],
        ),
    ]
