# Generated by Django 3.1.1 on 2020-10-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0008_legend'),
    ]

    operations = [
        migrations.AddField(
            model_name='legend',
            name='weight_classes',
            field=models.CharField(default='weight', max_length=30),
        ),
    ]
