# Generated by Django 3.1.1 on 2020-10-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0009_legend_weight_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legend',
            name='weight_classes',
            field=models.CharField(default='weight', max_length=100),
        ),
    ]
