# Generated by Django 3.1.1 on 2020-10-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0010_auto_20201022_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighters', models.CharField(max_length=200)),
                ('outcome', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BestKnockouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighters', models.CharField(max_length=200)),
                ('knockout_method', models.CharField(max_length=300)),
                ('knockout_round', models.IntegerField()),
                ('knockout_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BestSubmissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighters', models.CharField(max_length=200)),
                ('submission_method', models.CharField(max_length=300)),
                ('submission_round', models.IntegerField()),
                ('submission_time', models.TimeField()),
                ('submission_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('weight_class', models.IntegerField()),
                ('style', models.CharField(max_length=200)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField(default=0)),
                ('no_contests', models.IntegerField(default=0)),
                ('notable_wins', models.CharField(max_length=250)),
                ('title_obtained', models.CharField(max_length=100)),
            ],
        ),
    ]
