# Generated by Django 3.1.1 on 2020-10-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0012_auto_20201024_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestoftype',
            name='name',
        ),
        migrations.DeleteModel(
            name='Champions',
        ),
        migrations.DeleteModel(
            name='BestOfFights',
        ),
        migrations.DeleteModel(
            name='BestOfType',
        ),
    ]
