# Generated by Django 3.1.1 on 2020-10-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0013_auto_20201025_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestOfFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fighters', models.CharField(max_length=200)),
                ('event', models.CharField(max_length=200)),
                ('fight_date', models.DateField()),
                ('fight_winner', models.CharField(blank=True, max_length=300)),
                ('method_of_victory', models.IntegerField(null=True)),
                ('time_of_finish', models.TimeField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight_class', models.IntegerField()),
                ('style', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('draws', models.IntegerField(default=0)),
                ('title_reign', models.CharField(max_length=100)),
                ('no_contests', models.IntegerField(default=0)),
                ('notable_wins', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='BestOfType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('fights', models.ManyToManyField(max_length=200, to='backend_mma.BestOfFight')),
            ],
        ),
    ]
