# Generated by Django 3.1.1 on 2020-10-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0015_auto_20201025_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoftype',
            name='fights',
            field=models.ManyToManyField(blank=True, to='backend_mma.BestOfFight'),
        ),
    ]
