# Generated by Django 3.1.1 on 2020-10-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0016_auto_20201025_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestoffight',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
