# Generated by Django 3.1.1 on 2020-10-26 00:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0017_bestoffight_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestoffight',
            name='round_of_finish',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(50)], verbose_name='Round'),
        ),
    ]
