# Generated by Django 3.1.1 on 2020-10-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0021_auto_20201026_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffight',
            name='time_of_finish',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
