# Generated by Django 3.1.1 on 2020-10-26 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0022_auto_20201026_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffight',
            name='round_of_finish',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='bestoffight',
            name='time_of_finish',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
