# Generated by Django 3.1.1 on 2020-10-26 00:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0023_auto_20201026_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestoffight',
            name='title',
        ),
        migrations.AlterField(
            model_name='bestoffight',
            name='round_of_finish',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Round'),
        ),
    ]
