# Generated by Django 3.1.1 on 2020-10-26 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0024_auto_20201026_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffight',
            name='time_of_finish',
            field=models.TimeField(default=None),
        ),
    ]
