# Generated by Django 3.1.1 on 2020-10-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0026_auto_20201026_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestoffight',
            name='time_of_finish',
            field=models.CharField(default='05:00', max_length=10),
        ),
    ]
