# Generated by Django 3.1.1 on 2020-11-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mma', '0027_auto_20201026_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='example',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='example_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
