# Generated by Django 3.1.1 on 2020-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_bellatorvideos_fighthighlights_ufcvideos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMAPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=100)),
                ('playlist_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MMAVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_id', models.CharField(max_length=200, unique=True)),
                ('thumbnail_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='BellatorVideos',
        ),
        migrations.DeleteModel(
            name='FightHighlights',
        ),
        migrations.DeleteModel(
            name='UFCVideos',
        ),
        migrations.AddField(
            model_name='mmaplaylist',
            name='video',
            field=models.ManyToManyField(to='backend_api.MMAVideo'),
        ),
    ]
