# Generated by Django 3.1.1 on 2020-10-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_mmavideo_playlist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmaplaylist',
            name='video',
            field=models.ManyToManyField(blank=True, to='backend_api.MMAVideo'),
        ),
    ]
