# Generated by Django 3.1.1 on 2020-10-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_auto_20201016_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmaplaylist',
            old_name='video',
            new_name='playlist_video',
        ),
    ]
