# Generated by Django 3.1.1 on 2020-10-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_auto_20201016_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='mmaplaylist',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
